apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-dev
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: snapshot-99da91a9d5c68874335514fa627cfaec85bf08f7
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: snapshot-f72592b658bd435ce04a197957896c3ce30efaea
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: snapshot-f1410b7965e6acc0ddc73494e585421d2c4bf84d
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: snapshot-4c6cff5fac287c7f37e981efcf1d155381f0ff85
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: snapshot-4c6cff5fac287c7f37e981efcf1d155381f0ff85
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: snapshot-851ade1f549b30c1b8d79a19b65fbfd50e487dca
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
- patch: |
    - op: replace
      path: /subsets/0/addresses/0/ip
      value: 182.208.21.16
  target:
    kind: Endpoints
    name: technet
resources:
- ../base
