apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-dev
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: snapshot-d9d06d56b16993eb1417f79c01f91befb5f277cb
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: snapshot-453ebf524aefe32de8a5fd164552d8f8600d3fc7
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: snapshot-1406da637d7e5f0357e1d1998d72521e4fb20c56
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: snapshot-1406da637d7e5f0357e1d1998d72521e4fb20c56
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: pdf-gateway-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
- patch: |
    - op: replace
      path: /subsets/0/addresses/0/ip
      value: 182.208.21.16
  target:
    kind: Endpoints
    name: technet
resources:
- ../base
