apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-dev
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: snapshot-ce6f441b4c95b0f007f36cc85b9b2c4b821b49f9
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: snapshot-e3f54dc54cde188f471bb46c44a9da77dcec275f
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: snapshot-2b0e08133dbec86f4dfde73c2a1a382e2a824a98
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: snapshot-2b0e08133dbec86f4dfde73c2a1a382e2a824a98
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: pdf-gateway-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
- patch: |
    - op: replace
      path: /subsets/0/addresses/0/ip
      value: 182.208.21.16
  target:
    kind: Endpoints
    name: technet
resources:
- ../base
