apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-streamdocs
resources:
- ingress.yaml
- streamdocs.yaml
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs
  newTag: 5.12.40.3-RELEASE
- name: mariadb
  newTag: 10.7.3
