apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: streamdocsdemotechnetepapyruscom-streamdocs
spec:
  serviceName: streamdocs
  replicas: 1
  selector:
    matchLabels:
      service: streamdocs.demo.technet.epapyrus.com
      app: streamdocs
  template:
    metadata:
      labels:
        service: streamdocs.demo.technet.epapyrus.com
        app: streamdocs
    spec:
      containers:
        - name: streamdocs
          image: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs:5.11.15.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /ePapyrus/sd
              subPath: ./streamdocs
          env:
            - name: WAIT_FOR_IT
              value: localhost:3306
            - name: SD_JDBC_URL
              value: jdbc:mariadb://localhost:3306/streamdocs
            - name: SD_JDBC_USERNAME
              value: master
            - name: SD_JDBC_PASSWORD
              value: master
            - name: SD_JDBC_DRIVER_CLASS
              value: org.mariadb.jdbc.Driver
            - name: SD_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL5Dialect
            - name: SD_ADMIN_ID
              value: epapyrus
            - name: SD_ADMIN_NAME
              value: epapyrus
            - name: SD_ADMIN_PASSWORD
              value: epapyrus12#$
        - name: mariadb
          image: mariadb:10.7.3
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_USER
              value: master
            - name: MARIADB_PASSWORD
              value: master
            - name: MARIADB_DATABASE
              value: streamdocs
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
              subPath: ./mariadb
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs
        resources:
          requests:
            storage: 2Gi
