apiVersion: v1
kind: Service
metadata:
  name: streamdocsdevepapyruscom-streamdocs
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    service: streamdocs.dev.epapyrus.com
    app: streamdocs
