apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
- gitlab.yaml
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-ee
  newTag: 15.2.0-ee.0
