apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epapyrus
resources:
- gitlab.yaml
- ingress.yaml
images:
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-ee
  newTag: 15.2.0-ee.0
