apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epapyrus
resources:
- docsoup-homepage.yaml
- ingress.yaml
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/docsoup-homepage-client
  newTag: release-cef0348e3fc1df8be8c349ef8c2454b6edf7906d
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/docsoup-homepage-server
  newTag: release-cef0348e3fc1df8be8c349ef8c2454b6edf7906d
