apiVersion: v1
kind: Service
metadata:
  name: fg-demo-streamdocs
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    service: fg-demo
    app: streamdocs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fg-demo-streamdocs
  namespace: default
spec:
  serviceName: fg-demo-streamdocs
  replicas: 1
  selector:
    matchLabels:
      service: fg-demo
      app: streamdocs
  template:
    metadata:
      labels:
        service: fg-demo
        app: streamdocs
    spec:
      containers:
        - name: streamdocs
          image: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs:fg.demo.epapyrus.com--streamdocs
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WAIT_FOR_IT
              value: localhost:3306
            - name: STREAMDOCS_HOME
              value: /ePapyrus/sd
            - name: MARIADB_USER
              value: master
            - name: MARIADB_PASSWORD
              value: master
            - name: SD_DATABASE
              value: streamdocs
          volumeMounts:
            - name: storage
              mountPath: /ePapyrus/sd
              subPath: ./streamdocs
        - name: mariadb
          image: mariadb:10.7.3
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_USER
              value: master
            - name: MARIADB_PASSWORD
              value: master
            - name: MARIADB_DATABASE
              value: streamdocs
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
              subPath: ./mariadb
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs
        resources:
          requests:
            storage: 4Gi
