apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-dev
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: snapshot-8f197ac0b56980b842680df03e4d247a999c0206
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: snapshot-e634132bf3fd5c96b79e14361284102c624fa055
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: snapshot-b4df3cfd3f0554bf6c9331c35477c0d7bb8951bc
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: snapshot-b2154363037e3cc05ad5a76fd8b2ba0f1d984432
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: snapshot-b2154363037e3cc05ad5a76fd8b2ba0f1d984432
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: snapshot-31739d65ccb7ca5db0b6dfa5cf123fee1280d001
- name: mariadb
  newTag: 10.7.3
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.hq.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
- patch: |
    - op: replace
      path: /subsets/0/addresses/0/ip
      value: 182.208.21.16
  target:
    kind: Endpoints
    name: technet
resources:
- ../_base/technet
