apiVersion: v1
kind: Service
metadata:
  name: typedtestepapyruscom-streamdocs
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    service: typed.test.epapyrus.com
    app: streamdocs
