apiVersion: v1
kind: Service
metadata:
  name: gitlabepapyruscom
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gitlab.epapyrus.com
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    service: gitlab.epapyrus.com
