apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: license-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - license.epapyrus.com
    secretName: license.epapyrus.com-tls
  rules:
    - host: license.epapyrus.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: license-server
                port:
                  number: 8080
