apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-prod
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: release-613a259745daac3f820023a7f05ce0bbdfe02922
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: release-6f34bff8867a45d53085f73bd41e1ff08cc04e28
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: release-eda1ff6bec80064bf6c9d8961aad2e0d972f07a1
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: release-3d9d409e35ac07bf64f5d6f4edc939b23aad308e
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: release-3d9d409e35ac07bf64f5d6f4edc939b23aad308e
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: release-36e3fd1cfd6ed3b11bf3ac99fe916a6497062bb3
- name: mariadb
  newTag: 10.7.3
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
resources:
- ../_base/technet
