apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-prod
images:
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: release-f99900a68f68e1bdbebb0fee7ef72ede2cb319b3
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: release-b4791d0b2c774408ca4906ab27f2f84beca867db
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: release-3776d5a379f607c3d05ba683244e510153e956e2
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: release-095262602415ac6059e35564d5475c886edd2db6
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: release-095262602415ac6059e35564d5475c886edd2db6
- name: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: release-380fa8ea23d6fae69a53e3c17f34bee06ea84393
- name: mariadb
  newTag: 10.7.3
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
resources:
- ../_base/technet
