apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-prod
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: release-a6887cf4c9ee1708846f8886136b531c36491c77
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: release-11ec347759197f11feca2218e120ad295c6d6d0d
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: release-a2a8527456a56ee7f0bd9c23ab3000d78208dfca
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: release-488d73bda56ed4436c580a803c25f8aac3849213
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: release-488d73bda56ed4436c580a803c25f8aac3849213
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: release-035814e502f9640c05583ad92de95227b2df29e5
- name: mariadb
  newTag: 10.7.3
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
resources:
- ../_base/technet
