apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-prod
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: release-c0ee11a118df9caab25be51d61d29ba47a3fbbcc
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: release-23e96cc513875d2e68e43afda59b0d1cef32f166
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: release-6f657fe3976b07e4d8538c14e8f8ba541b749c1b
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: release-4ca4b8126af37faeebc28e2d282f7a04114facce
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: release-4ca4b8126af37faeebc28e2d282f7a04114facce
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: release-fe0bc92b256b1cc12466b2f7a4216b1c2fb4931c
- name: mariadb
  newTag: 10.7.3
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
resources:
- ../_base/technet
