apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-prod
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-11-guide-assets
  newTag: release-17979d1ea5448df48f637a786605971a7020a764
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: release-672572c6dc7096a99331011428db4946432b383a
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: release-4d1336d339e29bbe975e463d0e354dbdd40c0133
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: release-8c3f41bbc3b2ac0d41517863299f6ed2516b5ced
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: release-8c3f41bbc3b2ac0d41517863299f6ed2516b5ced
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/textsense-guide-assets
  newTag: release-608d93165663fd75953bc1419a3727c0bb4c2541
- name: mariadb
  newTag: 10.7.3
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
resources:
- ../_base/technet
