apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsletter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - news.test.epapyrus.com
      secretName: news.test.epapyrus.com-tls
  rules:
    - host: news.test.epapyrus.com
      http:
        paths:
          - path: /streamdocs
            pathType: Prefix
            backend:
              service:
                name: streamdocs
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsletter-block-welcome
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: 182.208.21.16/32
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - news.test.epapyrus.com
      secretName: news.test.epapyrus.com-tls
  rules:
    - host: news.test.epapyrus.com
      http:
        paths:
          - path: /streamdocs/view/welcome
            pathType: Prefix
            backend:
              service:
                name: streamdocs
                port:
                  number: 8080
