apiVersion: v1
kind: Service
metadata:
  name: streamdocs
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: streamdocs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: streamdocs
spec:
  serviceName: streamdocs
  replicas: 1
  selector:
    matchLabels:
      app: streamdocs
  template:
    metadata:
      labels:
        app: streamdocs
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - db
      containers:
        - name: streamdocs
          image: 010438473788.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WAIT_FOR_IT
              value: 'localhost:3306'
            - name: SD_JDBC_URL
              value: 'jdbc:mariadb://localhost:3306/streamdocs'
            - name: SD_JDBC_USERNAME
              value: epapyrus
            - name: SD_JDBC_PASSWORD
              value: epapyrus12#$
            - name: SD_JDBC_DRIVER_CLASS
              value: org.mariadb.jdbc.Driver
            - name: SD_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL5Dialect
          volumeMounts:
            - name: storage
              mountPath: /ePapyrus/sd
              subPath: ./streamdocs
        - name: mariadb
          image: mariadb:latest
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_USER
              value: epapyrus
            - name: MARIADB_PASSWORD
              value: epapyrus12#$
            - name: MARIADB_DATABASE
              value: streamdocs
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
              subPath: ./mariadb
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs
        resources:
          requests:
            storage: 4Gi
