apiVersion: v1
kind: Service
metadata:
  name: newsletter-streamdocs
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: streamdocs
    service: newsletter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: newsletter-streamdocs
spec:
  serviceName: newsletter-streamdocs
  replicas: 1
  selector:
    matchLabels:
      app: streamdocs
      service: newsletter
  template:
    metadata:
      labels:
        app: streamdocs
        service: newsletter
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - db
      containers:
        - name: streamdocs
          image: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WAIT_FOR_IT
              value: db:3306
            - name: JAVA_OPTS
              value: -Dspring.profiles.active=mysql
          volumeMounts:
            - name: storage
              mountPath: /ePapyrus/sd
              subPath: ./streamdocs
        - name: mariadb
          image: mariadb:latest
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_USER
              value: epapyrus
            - name: MARIADB_PASSWORD
              value: epapyrus12#$
            - name: MARIADB_DATABASE
              value: streamdocs
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
              subPath: ./mariadb
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs
        resources:
          requests:
            storage: 4Gi
