apiVersion: v1
kind: Service
metadata:
  name: licenseepapyruscom
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    service: license.epapyrus.com
