apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: technet-prod
images:
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/pdf-gateway-guide-assets
  newTag: release-665c141e876ada4794adb8740362df76a5938584
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/streamdocs-guide-assets
  newTag: release-eab038614e52e20bc132fb78cfbf98693ba2a4f6
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-client
  newTag: 2.1.5
- name: 730490031339.dkr.ecr.ap-northeast-2.amazonaws.com/technet-server
  newTag: 2.1.5
patchesStrategicMerge:
- ./ingress-patch.yaml
- ./server-patch.yaml
- ./technet-doc-volume-patch.yaml
patchesJson6902:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: technet
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: pdf-gateway-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-doc
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: technet.epapyrus.com
  target:
    kind: Ingress
    name: streamdocs-tutorial
- patch: |
    - op: replace
      path: /subsets/0/addresses/0/ip
      value: 52.79.246.47
  target:
    kind: Endpoints
    name: technet
resources:
- ../base
