apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technet-doc
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamdocs-doc
spec:
  template:
    spec:
      nodeSelector:
        technet-doc: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-gateway-11-doc
spec:
  template:
    spec:
      nodeSelector:
        technet-doc: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-gateway-doc
spec:
  template:
    spec:
      nodeSelector:
        technet-doc: prod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
spec:
  template:
    spec:
      nodeSelector:
        technet-doc: prod
